### ISSUE TITLE
Make "Stall" label stay in the center

### ISSUE THREAD

**Issue by Whebon** [Whebon/dale-of-merchants#20]
Make "Stall" stay in the center of the stall, even when more width is available.

https://github.com/user-attachments/assets/91272c37-8a1a-45ab-a38e-cbca3174b478

**Minimal example:**
Make it such that the title is always exactly above the center 'stack-container'.

```html
<div class="stall-wrap">
  <h3>Title</h3>
  <div class="stall-container">
    <div class="stack-container"></div>
    <div class="stack-container"></div>
    <div class="stack-container"></div>
    <div class="stack-container"></div>
    <div class="stack-container"></div>
    <!-- Possibly more "stack-container"s -->
  </div>
</div>
```

```css
.stall-wrap {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 0px;
  margin-bottom: 0px;
  margin-left: 10px;
  margin-right: 10px;
  padding-top: 0px;
  flex: 1 1;
}
.stall-container {
  width: 100%;
  display: flex;
  flex: 1 1;
  justify-content: left;
}
.stack-container {
  flex: 1 1;
  background-color: red;
  border: 2px solid black;
  margin-left: 5px;
  max-width: 100px;
  height: 100px;
  position: relative;
}
```
