### ISSUE TITLE
Calculate modified values on the client side

### ISSUE THREAD

**Issue by Whebon** [Whebon/dale-of-merchants#49]
The client should be informed about ongoing effects (such as Flashy Shows) to display modified card values. Add a QoL feature that displays the total value of the currently selected cards for the “build” and “stall” actions.

**Comment by Whebon** [comment]
Done

Displaying the sum might be a bit of an overkill

**Comment by Whebon** [comment]
```css
element.style {
    position: absolute;
    left: 10px;
    border-radius: 10px;
    padding: 5px;
    min-width: 20px;
}

.daleofmerchants-label {
    ...
}
```

<img width="1120" height="843" alt="Image" src="https://github.com/user-attachments/assets/84488be2-2e60-4cca-8957-7dd807122d55" />
