### ISSUE TITLE
Smooth limbo transition (`dale-hidden-transitioning`)

### ISSUE THREAD

**Issue by Whebon** [Whebon/dale-of-merchants#54]
Smoothly let limbo (dis)appear using a css transition. I have attempted to make this work for a couple of ours. But I couldn't get it to work with the Stock's `updateDisplay()`

```ts
//limbo transition
const thiz = this;
const duration = 500;
const limboTransitionUpdateDisplay = () => {
	console.log("limboTransitionUpdateDisplay");
	setTimeout(function() {thiz.myLimbo.updateDisplay()}, duration+1)
	setTimeout(function() {thiz.myHand.updateDisplay()}, duration+1)
}
const onLimboItemCreate = () => {
	const classList = thiz.myLimbo.wrap!.classList;
	if (classList.contains("dale-hidden")) {
		classList.remove("dale-hidden");
		classList.add("dale-hidden-transitioning");
		setTimeout(() => {
			classList.remove("dale-hidden-transitioning");
		}, 1);
		limboTransitionUpdateDisplay();
	}
}
const onLimboItemDelete = () => {
	const classList = thiz.myLimbo.wrap!.classList;
	if (thiz.myLimbo.count() <= 1) {
		if (!classList.contains("dale-hidden") && !classList.contains("dale-hidden-transitioning")) {
			classList.add("dale-hidden-transitioning")
			setTimeout(() => {
				classList.remove("dale-hidden-transitioning");
				classList.add("dale-hidden");
			}, duration)
			limboTransitionUpdateDisplay();
		}
	}
}
```

```css
#dale-myhand-wrap {
	flex-grow: 1;
}

#dale-mylimbo-wrap {
	flex-grow: 0;
	min-width: 35%;
	transition: padding 0.5s, min-width 0.5s; //should match the js for "dale-hidden-transitioning"
	&.dale-hidden-transitioning {
		min-width: 0;
		padding: 0;
		.dale-label {
			color: transparent;
			padding: 0px 0px;
			width: 0px;
		}
	}
	&.dale-hidden {
		display: none;
		min-width: 0;
		padding: 0;
		.dale-label {
			display: none;
		}
	}
}

.dale-arc-stock {
	.dale-label {
		color: white;
		padding: 10px 15px;
		border-radius: 0 0 10px 10px;
		display: inline-block;
		margin-bottom: 20px;
		transition: color 0.5s, color 0.5s, width 0.5s; //should match the js for "dale-hidden-transitioning"
	}
}
```
