### ISSUE TITLE
Tooltip blocks pointer events

### ISSUE THREAD

**Issue by Whebon** [Whebon/dale-of-merchants#79]
Issues with snapping:

https://github.com/user-attachments/assets/3d91925a-ab7b-42bb-ae05-cfaedaaf4ffd

**Comment by Whebon** [comment]
The pointer event was blocked by:

```html
<div class="dijitTooltip dijitTooltipRight" id="dijit__MasterTooltip_0" data-dojo-attach-event="mouseenter:onMouseEnter,mouseleave:onMouseLeave" widgetid="dijit__MasterTooltip_0" style=""><div class="dijitTooltipConnector" data-dojo-attach-point="connectorNode" style="top: 54.6875px;"></div><div class="dijitTooltipContainer dijitTooltipContents" data-dojo-attach-point="containerNode" role="alert" align="left"></div></div>
```

The following css fixed it, hopefully it did not break anything:

```scss
.dijitTooltip {
	pointer-events: none;
	div {
		pointer-events: none;
	}
}
.dijitTooltipContainer {
	pointer-events: none;
}
```
